### ISSUE TITLE
Value mapping wind gust/speed

### ISSUE THREAD

**Issue by freemann** [pilotak/homeassistant-clientraw#1]
I'm checking stuff because some wind value didn't match with weather conditions and noticed some "mismatching" based on a online wd clientraw parser.
Don't know if the parser is good, but it could be a point to discus and see where its going wrong (my assumptions, the online parser of this plugin).

The parser i'm using;
https://saratoga-weather.org/wdparser.php

I see the plugin is using element
[1] = "wind"
[2] = "wind_gust".

But the parser shows me these values are;
1 = "Average Windspeed (avg last 60 secs)"
2 = "Current Windspeed"

Looking in the Parser for me value/element 2 would fit for wind_gust element [1]
Looking in the Parser for me value/element 71 or 140 would fit for wind_gust element [2]
So in the plugin;
wind = 2 =  "Current Windspeed"
wind_gust = 71/140 = "Max Wind Gust"/"Max Gust In Last Min"

Let me known what you think about it!

**Comment by pilotak** [comment]
Sorry for the late answer i had notifications turned off. I believe this is now fixed through your PR?

**Comment by belidi** [comment]
is it possible to recover the values for the maximum and minimum temperature of the day

**Comment by pilotak** [comment]
@belidi i believe it is possible, please open separate issue
