### ISSUE TITLE
wind gust / wind speed

### ISSUE THREAD

**Issue by massimilianodossi** [pilotak/homeassistant-clientraw#10]
I think that the wind speed is wrong, 
in that field I detect the gust, 
the correct value is the field "2 - current windspeed"

**Comment by pilotak** [comment]
`wind_speed` is: "Average Windspeed (avg last 60 secs)" field 1, which i think is more suitable for this integration as you don't poll the information that often.

`wind_gust_day`: "Max Wind Gust" field 71

If you want the the field 2, it can be added there. But i'm open for discussion

**Comment by massimilianodossi** [comment]
sorry but with your wind_speed i see a wrong value respect the real average of 60sec.
so can you insert the current speed ? 
Thank you for your work.

**Comment by pilotak** [comment]
as you can see it's field 1, maybe your clientraw generator is different? https://github.com/pilotak/homeassistant-clientraw/blob/463965ce4f460c2943bd900c5981be6984edb3a8/custom_components/clientraw/sensor.py#L299-L302

Do you think it's better to change it to field 2 and add field 1 as `wind_speed_avg_60s`
or
keep it as it is and add `current_wind_speed` as field 2?

**Comment by massimilianodossi** [comment]
yes, i think it's better to change the "wind_speed" to field 2

**Comment by pilotak** [comment]
updated in version 2.2.0
