### ISSUE TITLE
Request max Gust today

### ISSUE THREAD

**Issue by Quart666** [pilotak/homeassistant-clientraw#19]
Hi
I don know if this is the right place to add a feature request.
But I would like to have the value for the highest Gust today

**Comment by pilotak** [comment]
Hi, this is definitely a right place! It's quite easy to add this feature, you can follow https://github.com/pilotak/homeassistant-clientraw/pull/16/files

**Comment by pilotak** [comment]
@Quart666 i looked at the data, this should at position 71, which is already added as `wind_gust_day`
