### ISSUE TITLE
unit conversion issue now..

### ISSUE THREAD

**Issue by ktn7419** [pilotak/homeassistant-clientraw#22]
I update in Home Assistance and now see this one in the log:
"Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 285: temperature = convert_temperature(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 298: temperature = convert_temperature(
Detected integration that uses pressure utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.PressureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 381: pressure = round(convert_pressure(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 439: temperature = convert_temperature("

Looks like a new issue?

**Comment by pilotak** [comment]
This is a new issue, yes. I don't have that on my setup but this is maybe due to using metric system. Please try #23

**Comment by ktn7419** [comment]
Hello Pavel,

Looks like one more conversion issue:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 5:33:22 PM (1 occurrences)
Last logged: 5:33:22 PM

Detected integration that uses pressure utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.PressureConverter instead. Please report issue to the custom integration author for clientraw using this method at custom_components/clientraw/sensor.py, line 381: pressure = round(convert_pressure(

Gary

Thursday, December 15, 2022, 11:22:41 AM, you wrote:


This is a new issue, yes. I don't have that on my setup but this is maybe due to using metric system. Please try #23
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



-- 
Best regards,
 Gary                            ***@***.***

**Comment by pilotak** [comment]
could you please try it again?

**Comment by ktn7419** [comment]
Hello Pavel,

All set. Thank you.

Merry Christmas and a safe New Year to you.

Gary

Friday, December 16, 2022, 2:47:45 AM, you wrote:


could you please try it again?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



-- 
Best regards,
 Gary                            ***@***.***
