### ISSUE TITLE
Request for Wind-Chill

### ISSUE THREAD

**Issue by Kvarnbryggan** [pilotak/homeassistant-clientraw#24]
Hi
In Sweden it's getting a bit cold outside these days.
Right now the temprature is -13.5C but it feels like -17.3C as it is now almost no wind.
It is pressented in posision 44 in clientraw.txt, and there is also a max and min value at 77 and 78

I managed to add these my self by adding a couple of rows in sensor.py

First below row

 39   'temp': ['Temperature', TEMP_CELSIUS, TEMP_FAHRENHEIT, 'mdi:thermometer'],

I added these 3 rows as row

    'wind_chill': ['Wind Chill', TEMP_CELSIUS, TEMP_FAHRENHEIT, 'mdi:thermometer'],
    'wind_chill_max': ['Today MAX Wind Chill', TEMP_CELSIUS, TEMP_FAHRENHEIT, 'mdi:thermometer'],
    'wind_chill_min': ['Today MIN Wind Chill', TEMP_CELSIUS, TEMP_FAHRENHEIT, 'mdi:thermometer'],
 

Then below

279            elif dev.type == 'temp':
280                if self.data[4] != '-' and self.data[4] != '--' \
281                        and self.data[4] != '---':
282                    temperature = float(self.data[4])
283
284                    if self.hass.config.units is not METRIC_SYSTEM:
285                        temperature = TemperatureConverter.convert(
286                            temperature, TEMP_CELSIUS, TEMP_FAHRENHEIT)
287
288                    new_state = round(temperature, 2)
289                else:
290                    new_state = STATE_UNAVAILABLE

I added this section

            elif dev.type == 'wind_chill':
                if self.data[44] != '-' and self.data[44] != '--' \
                        and self.data[44] != '---':
                    temperature = float(self.data[44])

                    if self.hass.config.units is not METRIC_SYSTEM:
                        temperature = TemperatureConverter.convert(
                            temperature, TEMP_CELSIUS, TEMP_FAHRENHEIT)

                    new_state = round(temperature, 2)
                else:
                    new_state = STATE_UNAVAILABLE

            elif dev.type == 'wind_chill_max':
                if self.data[77] != '-' and self.data[77] != '--' \
                        and self.data[77] != '---':
                    temperature = float(self.data[77])

                    if self.hass.config.units is not METRIC_SYSTEM:
                        temperature = TemperatureConverter.convert(
                            temperature, TEMP_CELSIUS, TEMP_FAHRENHEIT)

                    new_state = round(temperature, 2)
                else:
                    new_state = STATE_UNAVAILABLE

            elif dev.type == 'wind_chill_min':
                if self.data[78] != '-' and self.data[78] != '--' \
                        and self.data[78] != '---':
                    temperature = float(self.data[78])

                    if self.hass.config.units is not METRIC_SYSTEM:
                        temperature = TemperatureConverter.convert(
                            temperature, TEMP_CELSIUS, TEMP_FAHRENHEIT)

                    new_state = round(temperature, 2)
                else:
                    new_state = STATE_UNAVAILABLE

And ofcouse I added wind_chill, wind_chill_max and wind_chill_min to monitored_conditions: under sensors

I got it working, but it would be nice to have it in the correct repository, so it will keep working after an update ;)

Regards Peter!

**Comment by pilotak** [comment]
Hi Peter,
thanks for the update, well done! you can easily submit a PR and become a contributor should you wish. Or i can of course do it too, it up to you

You can follow https://github.com/pilotak/homeassistant-clientraw/pull/16/files

**Comment by Kvarnbryggan** [comment]
I'm no devoloper, I've never submitted anything to GitHub. And I don't know how to do it.
I'm maybe a good copy/paster, but thats all ;)

Please go a head and submit the changes, maube if I look in to this later I can get back to you and becom a contributor.

///Peter!
