### ISSUE TITLE
Integration error on Home Assistant 2023.6.1

### ISSUE THREAD

**Issue by ebaschiera** [pilotak/homeassistant-clientraw#26]
Hi,
on Home Assistant 2023.6.1 Clientraw stopped working with the following error:

```
Logger: homeassistant.components.sensor
Source: custom_components/clientraw/sensor.py:587
Integration: Sensore (documentation, issues)
First occurred: 10 giugno 2023 alle ore 12:52:44 (1 occurrences)
Last logged: 10 giugno 2023 alle ore 12:52:44

Error while setting up clientraw platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/clientraw/sensor.py", line 116, in async_setup_platform
    await weather.async_update()
  File "/config/custom_components/clientraw/sensor.py", line 587, in async_update
    await asyncio.wait(tasks)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

Thanks!

**Comment by vk2him** [comment]
It's caused by Python being updated to v3.11 in HA 2023.6.0

**Comment by Kvarnbryggan** [comment]
What I understand asyncio was depricated in python 3.8 and removed from removed from 3.11
The question is how much has to be rewritten to get it working again?

///Peter!

**Comment by pilotak** [comment]
> The question is how much has to be rewritten to get it working again?

I will need to look at it, or maybe some can submit a PR?

**Comment by Quart666** [comment]
Any news ?
Or is there any integrations för WD or Davis WeatherlinkIP ?

**Comment by systeemi** [comment]
I hope at we get new version of this parser. And if there is possibility include solar and uv sensor to new version of parser.

**Comment by pilotak** [comment]
@Quart666 you need to understard that this my personal project that i released for anyone without any support or
quaranteed fix time! Once i find the spare time, i will fix it, because i will need to eventualy need to switch to new version of HA. If anyone is able to fix it earlier i'm happy to test and release.

**Comment by pilotak** [comment]
>  include solar and uv sensor to new version of parser

Need to know the index, please see https://github.com/pilotak/homeassistant-clientraw/pull/25/files it isn't that difficult to add a new sensor... but please open different issue

**Comment by systeemi** [comment]
I just use your code.. I don't understand coding at all.
I really respect what you are doing for us!
Is here a donate option?

**Comment by pilotak** [comment]
@systeemi please open new issue

**Comment by ha-bpratt** [comment]
appreciate your efforts with this project of yours.

I find it very handy to be able to get the details of my own weather station up in to HA with this clientraw parser.

I wish I knew how to code, because I'd love to be able to contribute.

**Comment by pilotak** [comment]
Please try #28

**Comment by vk2him** [comment]
Perfect - #28 fixes it - many thanks!!!!!!!
