### ISSUE TITLE
Add solar & UV

### ISSUE THREAD

**Issue by systeemi** [pilotak/homeassistant-clientraw#27]
what if clientraw parser included solar and uv sensors? Some of we have possibility to get our weather stations solar and  uv readings, so i woudl be nice to get that to HA

**Comment by pilotak** [comment]
there are two solars, which one?

34	Solar: Current reading (0% - 100%))	(Number)
127	Solar: VP Solar W/sqM (0 - 1800 W/sqM)	(Number)

**Comment by systeemi** [comment]
127 is the right one. It shows the irradation value which is the W/squaremeter.

I dont have any glue what it's current reding....

**Comment by pilotak** [comment]
@systeemi could you please test
