### ISSUE TITLE
temp max and min for the day 

### ISSUE THREAD

**Issue by belidi** [pilotak/homeassistant-clientraw#3]
is it possible to recover the values for the maximum and minimum temperature of the day ?

**Comment by pilotak** [comment]
i have pushed an update to master, could you please try?

**Comment by belidi** [comment]
sorry, but does not work with me. the sensors (sensor.clientraw_temp_min_day, temp_max_day) do not appear in "state"

**Comment by belidi** [comment]
sorry, my apologies, it works i made a mistake by modifying the configuration file, great
