### ISSUE TITLE
Deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by pbill2003** [pilotak/homeassistant-clientraw#32]
Hi

I'm a happy users of  homeassistant-clientraw for a few years & recently updated to clientraw v2.6.1 & HACore 2024.8.3 

I see this message in home-assistant.log

WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from clientraw, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'clientraw' custom integration
WARNING (ImportExecutor_0) [homeassistant.const] TEMP_FAHRENHEIT was used from clientraw, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please report it to the author of the 'clientraw' custom integration
WARNING (ImportExecutor_0) [homeassistant.const] PRESSURE_HPA was used from clientraw, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead, please report it to the author of the 'clientraw' custom integration
WARNING (ImportExecutor_0) [homeassistant.const] PRESSURE_INHG was used from clientraw, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.INHG instead, please report it to the author of the 'clientraw' custom integration
WARNING (ImportExecutor_0) [homeassistant.const] LENGTH_METERS was used from clientraw, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please report it to the author of the 'clientraw' custom integration
WARNING (ImportExecutor_0) [homeassistant.const] LENGTH_FEET was used from clientraw, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.FEET instead, please report it to the author of the 'clientraw' custom integration
WARNING (ImportExecutor_0) [homeassistant.const] LENGTH_INCHES was used from clientraw, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.INCHES instead, please report it to the author of the 'clientraw' custom integration

Please could you take a look when you have time? Many thanks.

**Comment by pilotak** [comment]
Hello,
thanks for reporting the issue. At least i have time to fix until January. If you would like to submit a PR i'm happy to review

**Comment by NotFU1** [comment]
As mentioned above. HA versions>
Core 2025.1.0b2
Supervisor 2024.12.1
Operating System 14.1
Frontend 20241224.0

When checking the config via  dev tools


Configuration warnings
Platform error 'sensor' from integration 'clientraw' - cannot import name 'TEMP_CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

And all the entities configured are unknown.

**Comment by NotFU1** [comment]
Many Thanks for this, appreciate youre efforts.. working fine after upgrade.

**Comment by pilotak** [comment]
good to hear
