### ISSUE TITLE
Can Indoor temp be added

### ISSUE THREAD

**Issue by vk2him** [pilotak/homeassistant-clientraw#4]
It would be great if Indoor temp could be added? Any reason the others such as Solar can't be aded?

**Comment by pilotak** [comment]
There are many that could be added, all of this is manual work. I can add indoor temp for you.

I'm also happy to accept pull requests should you wish to submit some 🙂

**Comment by vk2him** [comment]
Thanks Pavel,

I just looked at sensor.py file and realised it would be easy for me to do this myself. 

I also noticed something strange on how you're calculating wind gust - You're taking the current real-time wind reading and multiplying it by a scaling factor? I'm not sure if you knew that position 133 is Max Wind Gust in last hour and 140 is max gust in last minute?

There is an online clientraw.txt parser that helps decode each attribute that you might find helpful? 

https://saratoga-weather.org/wdparser.php

I'll add a few new ones and "fix" the gust in sensor.py and add a pull request soon.

Cheers Ian

**Comment by vk2him** [comment]
I've just finished adding extra elements to sensor.py, and I fixed a few areas that looked wrong.

1) As mentioned above, I'm now using 133 for gust
2) The forecast array for that uses  the Forecast icon (15) was wrong - it had too many elements so I fixed that.

Let me know what you think, I created a fork with the changes.

**Comment by pilotak** [comment]
please submit a pull request so i can comment on it

**Comment by vk2him** [comment]
Ok pull request done

**Comment by pilotak** [comment]
fix #5
